### ISSUE TITLE
Use forge:seeds & minecraft:seeds tag for the recipes

### ISSUE THREAD

**Issue by Cynix32** [CodersDownUnder/growablecells2#1]
It would just be neat if the mod could use tags so that even seeds from other mods could be used instead of just being specifically wheat seeds.

**Comment by Trhod17** [comment]
Im currently working on this feature, but a mixture of issues with the config system and limited free time its taking longer than anticipated

**Comment by Trhod17** [comment]
Update released https://www.curseforge.com/minecraft/mc-mods/growable-cells-2/files/3408005
