### ISSUE TITLE
Only the extra storage 1048576k fluid disk will harvest

### ISSUE THREAD

**Issue by XiaoKe89** [CodersDownUnder/growablecells2#4]
**Versions**
Minecraft: 1.19.2
Forge: 43.1.47
Growable Cells: 1.19.2-4.0.0
Applied Energistics(If Applicable): 12.8.4
Refined Storage(If Applicable): 1.11.1
Extra Disks(If Applicable): N/A
Extra Storage(If Applicable): 1.19.2-3.0.1

**Describe the bug**
Only the extra storage 1048576k fluid disk is working. All other disks will grow but nothing drops not even the seed.

**To Reproduce**
1. Plant seed
2. grow seed
3. harvest seed

**Expected behavior**
Harvesting the fully grown crop should drop the proper disk and seed

**Additional context**
Looking at the recipes in the mod file it looks like all the disks have the info for the extra storage 1048576k fluid disk so looks like something got messed up when porting the mod over

**Comment by Trhod17** [comment]
Fixed https://www.curseforge.com/minecraft/mc-mods/growable-cells-2/files/4083683
